name:                ollama-haskell
version:             0.2.1.0
github:              "tusharad/ollama-haskell"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2024 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Haskell client for ollama.
category:            Web
description:         Ollama client for Haskell

dependencies:
- aeson >= 2 && < 3
- base >= 4.7 && < 5
- base64-bytestring >= 1 && < 2
- bytestring >= 0.10 && < 0.13
- containers >= 0.6 && < 0.9
- directory >= 1 && < 1.4
- filepath >= 1 && < 1.6
- http-client >= 0.6 && < 0.8
- http-client-tls >= 0.2 && < 0.4
- http-types >= 0.7 && < 0.13
- mtl >= 2 && < 3
- stm >= 2 && < 3
- text >= 1 && < 3
- time >= 1 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - ImportQualifiedPost

tests:
  ollama-haskell-test:
    main:                Main.hs
    source-dirs:         test
    default-extensions:
      - ImportQualifiedPost
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - ollama-haskell
    - scientific
    - silently
    - tasty >= 1.5
    - tasty-hunit
    - text
